defaults: &defaults
  token: 958a1bb5e951022317eba0835b9f1229c3eecac185584af3b61262e390b195dee85610b672bcc1492fb9e2f816d77d65f2f8a2ee751d816683e05a8ea2167321
  app_name: Rails 3 Saas example site
  noreply: noreply@fs-rails3-saas.heroku.com
  host: localhost:3000

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  host: fs-rails3-saas.heroku.com
